name: Laravel

on:
  release:
    types: [published]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Create deployment artifact
      run: tar -czf laractrl.tar.gz --exclude=*.git --exclude=node_modules *

    - name: Store artifact for distribution
      uses: actions/upload-artifact@v3
      with:
        name: laractrl
        path: laractrl.tar.gz
